# Generated by Django 5.2 on 2025-04-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='price',
            new_name='amount',
        ),
    ]
