# Generated by Django 5.2 on 2025-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
