# Generated by Django 5.2 on 2025-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments_session_id_payments_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
